title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: featured_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Featured Image'
          -
            import: rich_text
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: date
            field:
              type: date
              display: Date
          -
            handle: categories
            field:
              type: terms
              taxonomies:
                - categories
              display: Categories
              mode: select
